services:
  web:
    image: custom-django
    build: .
    ports:
      - 8000:8000
    volumes:
      - dev-static-data:/vol/web
    command: >
      sh -c  "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=benjamin is cool
      - POSTGRES_USERNAME=benji
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
  
  
volumes:
  postgres_db_data:
  dev-static-data:
