version: '3.10'

services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build: .

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env